plugins:
  - jekyll-remote-theme
remote_theme: mmistakes/so-simple-theme

locale: en-US
title: "COVID 19 Study"
description: "A study of the impacts of COVID-19 and social distancing."
baseurl: ""
url: https://covid19.ut-wcwh.org

sass:
  sass_dir: _sass
  style: compressed
  
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

google_analytics: UA-143032343-1
